### ISSUE TITLE
How to set 8k tokens output ?

### ISSUE THREAD

**Issue by RomDlg** [jjleng/copilot-more#3]
Hey, I wonder if its possible to set 8k tokens output to use in cline. it can help a lot to dont get cutoff output error

**Comment by jjleng** [comment]
Yes. you can modify `preprocess_request_body` in `server.py`

```
    return {
        **request_body,
        "messages": processed_messages,
        "max_tokens": 8192
    }
```
max_tokens just specify the the possible output token amount cap. However, this doesn't guarantee that the API will certainly output more tokens. Because:

-  LLM could stop generating earlier 
-  More output tokens will cause more kv cache usage, therefore more GPU VRAM. This may cause your request be terminated earlier due to resource exhaustion
-  MSFT definitely put some filters on the API. It could cause the API terminate earlier.

In my test, most of the time, my requests end with < 2500 tokens despite setting "max_tokens": 8192

**Comment by kaiwen-wang** [comment]
Also, I feel like MSFT is somehow silently/secretly retarding the output when you use this method instead of the Copilot Extension
